import type { Archetype, Budget, Product, Question } from "./types";

export const RECIPIENTS = [
  "Friend",
  "Partner",
  "Mother",
  "Father",
  "Sister",
  "Brother",
  "Colleague",
  "Other",
];

export const OCCASIONS = [
  "Birthday",
  "Graduation",
  "Anniversary",
  "Wedding",
  "Thank You",
  "Just Because",
  "Other",
];

export const BUDGETS: Budget[] = [
  { id: "under-100", label: "Under SAR 100", min: 0, max: 99 },
  { id: "100-250", label: "SAR 100–250", min: 100, max: 250 },
  { id: "250-500", label: "SAR 250–500", min: 250, max: 500 },
  { id: "500-1000", label: "SAR 500–1,000", min: 500, max: 1000 },
  { id: "1000-plus", label: "SAR 1,000+", min: 1000, max: 100000 },
];

export const ARCHETYPES: Record<string, Archetype> = {
  "cozy-creative": {
    id: "cozy-creative",
    name: "Cozy Creative",
    tagline: "Slow mornings, good books, and everything soft.",
    tags: ["Matcha", "Books", "Cozy", "Minimal"],
    accent: "#7f9070",
  },
  "tech-play": {
    id: "tech-play",
    name: "Tech & Play",
    tagline: "A clean setup, good gear, and something to tinker with.",
    tags: ["Gaming", "Technology", "Minimal", "Setup"],
    accent: "#4a2e56",
  },
  "style-glow": {
    id: "style-glow",
    name: "Style & Glow",
    tagline: "Polished, put-together, and quietly luxurious.",
    tags: ["Fashion", "Beauty", "Luxury", "Self-care"],
    accent: "#c4674a",
  },
  "active-outdoors": {
    id: "active-outdoors",
    name: "Active & Outdoors",
    tagline: "Always moving, always planning the next trip.",
    tags: ["Fitness", "Travel", "Outdoors", "Energy"],
    accent: "#5f7d6a",
  },
  "cafe-culture": {
    id: "cafe-culture",
    name: "Café & Culture",
    tagline: "Specialty coffee, sketchbooks, and good company.",
    tags: ["Coffee", "Art", "Social", "Creative"],
    accent: "#a4713d",
  },
};

/**
 * Demo catalog. Store names are fictional and prices are realistic demo values
 * in SAR. Nothing here is a real retailer listing.
 */
export const PRODUCTS: Product[] = [
  // ---------- Cozy Creative ----------
  {
    id: "matcha-kit",
    name: "Ceremonial Matcha Starter Kit",
    price: 189,
    store: "Nabat & Co.",
    image: "/products/matcha-kit.svg",
    tags: ["Matcha", "Cozy", "Creative"],
    archetype: "cozy-creative",
    why: "They love matcha and slow cafe rituals, and this lets them make it properly at home.",
    prefs: ["experiential", "practical"],
  },
  {
    id: "bookmark-set",
    name: "Linen Bookmark Set",
    price: 85,
    store: "Vellum Studio",
    image: "/products/bookmark-set.svg",
    tags: ["Books", "Minimal", "Cozy"],
    archetype: "cozy-creative",
    why: "A small, thoughtful upgrade for someone who always has a book going.",
    prefs: ["practical"],
  },
  {
    id: "tumbler",
    name: "Engraved Ceramic Tumbler",
    price: 145,
    store: "Almaya Goods",
    image: "/products/tumbler.svg",
    tags: ["Cozy", "Minimal", "Coffee"],
    archetype: "cozy-creative",
    why: "Personalised with their name, and it suits their warm, minimal taste.",
    prefs: ["personal", "practical"],
  },
  {
    id: "knit-throw",
    name: "Weighted Knit Throw",
    price: 420,
    store: "Hearth Supply",
    image: "/products/knit-throw.svg",
    tags: ["Cozy", "Minimal"],
    archetype: "cozy-creative",
    why: "Their whole aesthetic is soft and warm, and this is the centrepiece of a cosy corner.",
    prefs: ["home"],
  },
  {
    id: "floor-lamp",
    name: "Reading Nook Floor Lamp",
    price: 690,
    store: "Halcyon House",
    image: "/products/floor-lamp.svg",
    tags: ["Books", "Cozy", "Minimal"],
    archetype: "cozy-creative",
    why: "Turns any corner into the reading nook they keep talking about.",
    prefs: ["home"],
  },
  {
    id: "tea-set",
    name: "Handmade Stoneware Tea Set",
    price: 1150,
    store: "Nabat & Co.",
    image: "/products/tea-set.svg",
    tags: ["Matcha", "Cozy", "Art"],
    archetype: "cozy-creative",
    why: "Hand-thrown and one of a kind, a quiet luxury for their tea ritual.",
    prefs: ["unique", "luxe"],
  },

  {
    id: "candle-duo",
    name: "Beeswax Candle Duo",
    price: 68,
    store: "Hearth Supply",
    image: "/products/candle-duo.svg",
    tags: ["Cozy", "Minimal"],
    archetype: "cozy-creative",
    why: "Warm light and no harsh scent, exactly the mood they build their space around.",
    prefs: ["home"],
  },
  {
    id: "cushion-set",
    name: "Linen Throw Cushion Set",
    price: 340,
    store: "Hearth Supply",
    image: "/products/cushion-set.svg",
    tags: ["Cozy", "Minimal"],
    archetype: "cozy-creative",
    why: "Soft, textured, and neutral, the finishing touch for their reading corner.",
    prefs: ["home"],
  },
  {
    id: "book-ladder",
    name: "Oak Bookshelf Ladder",
    price: 780,
    store: "Halcyon House",
    image: "/products/book-ladder.svg",
    tags: ["Books", "Cozy", "Minimal"],
    archetype: "cozy-creative",
    why: "Somewhere to put the stack of books that never fits on the shelf.",
    prefs: ["home", "unique"],
  },
  {
    id: "armchair",
    name: "Cloud Reading Armchair",
    price: 1650,
    store: "Halcyon House",
    image: "/products/armchair.svg",
    tags: ["Cozy", "Books", "Minimal"],
    archetype: "cozy-creative",
    why: "The centrepiece gift, the chair they will read in for the next ten years.",
    prefs: ["luxe", "home"],
  },

  // ---------- Tech & Play ----------
  {
    id: "cable-trio",
    name: "Braided USB-C Cable Trio",
    price: 75,
    store: "Lumen Lab",
    image: "/products/cable-trio.svg",
    tags: ["Technology", "Setup", "Minimal"],
    archetype: "tech-play",
    why: "Unglamorous but genuinely useful, the thing every tech person keeps needing.",
    prefs: ["practical"],
  },
  {
    id: "keypad",
    name: "Low-Profile Mechanical Keypad",
    price: 235,
    store: "Northline",
    image: "/products/keypad.svg",
    tags: ["Gaming", "Setup", "Technology"],
    archetype: "tech-play",
    why: "A compact desk upgrade that fits their clean, minimal setup.",
    prefs: ["practical"],
  },
  {
    id: "light-bar",
    name: "Monitor Light Bar",
    price: 320,
    store: "Lumen Lab",
    image: "/products/light-bar.svg",
    tags: ["Gaming", "Setup", "Technology"],
    archetype: "tech-play",
    why: "Instantly makes their desk look like the setups they save.",
    prefs: ["home"],
  },
  {
    id: "charge-dock",
    name: "Three-in-One Charging Dock",
    price: 460,
    store: "Northline",
    image: "/products/charge-dock.svg",
    tags: ["Technology", "Minimal", "Setup"],
    archetype: "tech-play",
    why: "Clears the cable mess they complain about, in a finish that matches their desk.",
    prefs: ["practical", "home"],
  },
  {
    id: "headphones",
    name: "Over-Ear Studio Headphones",
    price: 890,
    store: "Lumen Lab",
    image: "/products/headphones.svg",
    tags: ["Technology", "Gaming", "Minimal"],
    archetype: "tech-play",
    why: "Serious sound for gaming and focus sessions, an upgrade they would notice daily.",
    prefs: ["luxe", "practical"],
  },
  {
    id: "keyboard",
    name: "Hot-Swap Mechanical Keyboard",
    price: 1290,
    store: "Northline",
    image: "/products/keyboard.svg",
    tags: ["Gaming", "Setup", "Technology"],
    archetype: "tech-play",
    why: "Customisable down to each switch, a gift they will keep tinkering with.",
    prefs: ["unique", "luxe"],
  },

  {
    id: "laptop-stand",
    name: "Aluminium Laptop Stand",
    price: 92,
    store: "Northline",
    image: "/products/laptop-stand.svg",
    tags: ["Technology", "Setup", "Minimal"],
    archetype: "tech-play",
    why: "Fixes the neck ache they complain about, and it looks the part on their desk.",
    prefs: ["practical"],
  },
  {
    id: "desk-mat",
    name: "Ultrawide Desk Mat",
    price: 280,
    store: "Northline",
    image: "/products/desk-mat.svg",
    tags: ["Setup", "Gaming", "Minimal"],
    archetype: "tech-play",
    why: "Ties the whole setup together, and it is the first thing they will notice.",
    prefs: ["home", "practical"],
  },
  {
    id: "gaming-mouse",
    name: "Wireless Gaming Mouse",
    price: 560,
    store: "Lumen Lab",
    image: "/products/gaming-mouse.svg",
    tags: ["Gaming", "Technology", "Setup"],
    archetype: "tech-play",
    why: "Low latency and no cable, a genuine upgrade for the hours they put in.",
    prefs: ["practical", "luxe"],
  },
  {
    id: "monitor",
    name: "Ultrawide Curved Monitor",
    price: 2100,
    store: "Lumen Lab",
    image: "/products/monitor.svg",
    tags: ["Gaming", "Technology", "Setup"],
    archetype: "tech-play",
    why: "The single upgrade that changes how their whole setup feels.",
    prefs: ["luxe"],
  },

  // ---------- Style & Glow ----------
  {
    id: "scrunchies",
    name: "Mulberry Silk Scrunchie Trio",
    price: 95,
    store: "Studio Qamar",
    image: "/products/scrunchies.svg",
    tags: ["Fashion", "Self-care", "Beauty"],
    archetype: "style-glow",
    why: "Small, pretty, and genuinely good for their hair, an easy everyday win.",
    prefs: ["practical"],
  },
  {
    id: "necklace",
    name: "Gold-Plated Initial Necklace",
    price: 220,
    store: "Studio Qamar",
    image: "/products/necklace.svg",
    tags: ["Fashion", "Luxury", "Minimal"],
    archetype: "style-glow",
    why: "Personalised with their initial, sentimental without being over the top.",
    prefs: ["personal", "luxe"],
  },
  {
    id: "vanity-mirror",
    name: "Dimmable Vanity Mirror",
    price: 390,
    store: "Halcyon House",
    image: "/products/vanity-mirror.svg",
    tags: ["Beauty", "Self-care", "Minimal"],
    archetype: "style-glow",
    why: "They care about getting ready properly, and this makes the whole ritual better.",
    prefs: ["home", "practical"],
  },
  {
    id: "scarf",
    name: "Cashmere-Blend Scarf",
    price: 540,
    store: "Studio Qamar",
    image: "/products/scarf.svg",
    tags: ["Fashion", "Luxury", "Cozy"],
    archetype: "style-glow",
    why: "Soft, elegant, and exactly the quiet-luxury register they dress in.",
    prefs: ["luxe"],
  },
  {
    id: "perfume",
    name: "Oud & Amber Eau de Parfum",
    price: 780,
    store: "Almaya Goods",
    image: "/products/perfume.svg",
    tags: ["Beauty", "Luxury", "Self-care"],
    archetype: "style-glow",
    why: "A warm, signature-worthy scent, the kind of gift they would never buy themselves.",
    prefs: ["luxe", "unique"],
  },
  {
    id: "tote",
    name: "Leather Weekender Tote",
    price: 1400,
    store: "Studio Qamar",
    image: "/products/tote.svg",
    tags: ["Fashion", "Luxury", "Travel"],
    archetype: "style-glow",
    why: "Polished enough for work, big enough for a weekend away.",
    prefs: ["luxe", "practical"],
  },

  {
    id: "sleep-mask",
    name: "Satin Sleep Mask & Pouch",
    price: 78,
    store: "Studio Qamar",
    image: "/products/sleep-mask.svg",
    tags: ["Self-care", "Beauty", "Luxury"],
    archetype: "style-glow",
    why: "Small luxury, used every single night, and it travels with them.",
    prefs: ["practical"],
  },
  {
    id: "jewellery-box",
    name: "Rose Gold Jewellery Box",
    price: 295,
    store: "Studio Qamar",
    image: "/products/jewellery-box.svg",
    tags: ["Fashion", "Luxury", "Minimal"],
    archetype: "style-glow",
    why: "Somewhere proper to keep the pieces they already love wearing.",
    prefs: ["home", "personal"],
  },
  {
    id: "silk-pillowcase",
    name: "Silk Pillowcase Pair",
    price: 610,
    store: "Halcyon House",
    image: "/products/silk-pillowcase.svg",
    tags: ["Self-care", "Luxury", "Cozy"],
    archetype: "style-glow",
    why: "Better for hair and skin, and it feels like a hotel every night.",
    prefs: ["luxe", "home"],
  },
  {
    id: "hoop-earrings",
    name: "Gold Hoop Earring Set",
    price: 1180,
    store: "Studio Qamar",
    image: "/products/hoop-earrings.svg",
    tags: ["Fashion", "Luxury", "Beauty"],
    archetype: "style-glow",
    why: "Classic, goes with everything, and the kind of piece they keep forever.",
    prefs: ["luxe"],
  },

  // ---------- Active & Outdoors ----------
  {
    id: "bottle",
    name: "Insulated Steel Water Bottle",
    price: 90,
    store: "Dunes & Co.",
    image: "/products/bottle.svg",
    tags: ["Fitness", "Outdoors", "Minimal"],
    archetype: "active-outdoors",
    why: "They are always training or out somewhere, and this goes everywhere with them.",
    prefs: ["practical"],
  },
  {
    id: "bands",
    name: "Resistance Band Set",
    price: 160,
    store: "Pinegrove",
    image: "/products/bands.svg",
    tags: ["Fitness", "Energy"],
    archetype: "active-outdoors",
    why: "A full workout that packs into a bag, good for someone who trains anywhere.",
    prefs: ["practical", "experiential"],
  },
  {
    id: "windbreaker",
    name: "Packable Windbreaker",
    price: 310,
    store: "Dunes & Co.",
    image: "/products/windbreaker.svg",
    tags: ["Outdoors", "Travel", "Fitness"],
    archetype: "active-outdoors",
    why: "Folds into its own pocket, made for the spontaneous trips they take.",
    prefs: ["practical"],
  },
  {
    id: "daypack",
    name: "Trail Daypack 22L",
    price: 520,
    store: "Pinegrove",
    image: "/products/daypack.svg",
    tags: ["Outdoors", "Travel", "Fitness"],
    archetype: "active-outdoors",
    why: "The right size for day hikes and travel, durable enough to last years.",
    prefs: ["practical"],
  },
  {
    id: "gps-watch",
    name: "GPS Running Watch",
    price: 950,
    store: "Northline",
    image: "/products/gps-watch.svg",
    tags: ["Fitness", "Technology", "Energy"],
    archetype: "active-outdoors",
    why: "Tracks every run and route, a real upgrade for someone chasing goals.",
    prefs: ["luxe", "practical"],
  },
  {
    id: "tent",
    name: "Two-Person Camping Tent",
    price: 1320,
    store: "Pinegrove",
    image: "/products/tent.svg",
    tags: ["Outdoors", "Travel"],
    archetype: "active-outdoors",
    why: "Turns a gift into actual weekends away, an experience rather than just an object.",
    prefs: ["experiential", "unique"],
  },

  {
    id: "travel-towel",
    name: "Quick-Dry Travel Towel",
    price: 72,
    store: "Dunes & Co.",
    image: "/products/travel-towel.svg",
    tags: ["Outdoors", "Travel", "Fitness"],
    archetype: "active-outdoors",
    why: "Packs down to nothing, and it lives permanently in their gym bag.",
    prefs: ["practical"],
  },
  {
    id: "foam-roller",
    name: "Foam Recovery Roller",
    price: 290,
    store: "Pinegrove",
    image: "/products/foam-roller.svg",
    tags: ["Fitness", "Energy"],
    archetype: "active-outdoors",
    why: "The recovery kit they keep saying they should get but never buy.",
    prefs: ["practical"],
  },
  {
    id: "running-shoes",
    name: "Trail Running Shoes",
    price: 720,
    store: "Dunes & Co.",
    image: "/products/running-shoes.svg",
    tags: ["Fitness", "Outdoors", "Energy"],
    archetype: "active-outdoors",
    why: "Proper grip for the trails they run, and a real step up from road shoes.",
    prefs: ["practical", "luxe"],
  },
  {
    id: "travel-case",
    name: "Hard-Shell Carry-On Case",
    price: 1450,
    store: "Dunes & Co.",
    image: "/products/travel-case.svg",
    tags: ["Travel", "Outdoors", "Minimal"],
    archetype: "active-outdoors",
    why: "They travel constantly, and this is the bag that survives all of it.",
    prefs: ["luxe", "practical"],
  },

  // ---------- Cafe & Culture ----------
  {
    id: "dripper",
    name: "Pour-Over Dripper & Filters",
    price: 98,
    store: "Nabat & Co.",
    image: "/products/dripper.svg",
    tags: ["Coffee", "Minimal", "Creative"],
    archetype: "cafe-culture",
    why: "They take coffee seriously, and this is the cheapest way to brew properly.",
    prefs: ["experiential", "practical"],
  },
  {
    id: "sketchbook",
    name: "Hand-Bound Sketchbook",
    price: 175,
    store: "Vellum Studio",
    image: "/products/sketchbook.svg",
    tags: ["Art", "Creative", "Books"],
    archetype: "cafe-culture",
    why: "Beautiful paper for someone who is always drawing or journalling in cafes.",
    prefs: ["personal", "unique"],
  },
  {
    id: "watercolors",
    name: "Watercolour Travel Set",
    price: 265,
    store: "Vellum Studio",
    image: "/products/watercolors.svg",
    tags: ["Art", "Creative", "Travel"],
    archetype: "cafe-culture",
    why: "Pocket-sized creativity, perfect for the way they like to spend an afternoon.",
    prefs: ["experiential", "unique"],
  },
  {
    id: "grinder",
    name: "Conical Burr Coffee Grinder",
    price: 480,
    store: "Nabat & Co.",
    image: "/products/grinder.svg",
    tags: ["Coffee", "Setup", "Minimal"],
    archetype: "cafe-culture",
    why: "The upgrade that actually changes how their coffee tastes.",
    prefs: ["practical", "experiential"],
  },
  {
    id: "instant-camera",
    name: "Instant Camera & Film Pack",
    price: 760,
    store: "Lumen Lab",
    image: "/products/instant-camera.svg",
    tags: ["Art", "Social", "Creative"],
    archetype: "cafe-culture",
    why: "They love documenting things, and this makes memories they can actually hold.",
    prefs: ["experiential", "personal"],
  },
  {
    id: "espresso",
    name: "Compact Espresso Machine",
    price: 1180,
    store: "Nabat & Co.",
    image: "/products/espresso.svg",
    tags: ["Coffee", "Setup", "Social"],
    archetype: "cafe-culture",
    why: "Their cafe habit moved home, the big-gesture gift for a coffee person.",
    prefs: ["luxe", "experiential"],
  },
  {
    id: "espresso-cups",
    name: "Hand-Thrown Espresso Cups",
    price: 88,
    store: "Nabat & Co.",
    image: "/products/espresso-cups.svg",
    tags: ["Coffee", "Art", "Minimal"],
    archetype: "cafe-culture",
    why: "Small, handmade, and they will use them every single morning.",
    prefs: ["unique"],
  },
  {
    id: "ink-set",
    name: "Fineliner & Ink Set",
    price: 255,
    store: "Vellum Studio",
    image: "/products/ink-set.svg",
    tags: ["Art", "Creative", "Minimal"],
    archetype: "cafe-culture",
    why: "Proper pens for someone who actually fills the sketchbooks they buy.",
    prefs: ["practical", "experiential"],
  },
  {
    id: "drawing-tablet",
    name: "Digital Drawing Tablet",
    price: 640,
    store: "Lumen Lab",
    image: "/products/drawing-tablet.svg",
    tags: ["Art", "Creative", "Technology"],
    archetype: "cafe-culture",
    why: "Opens up a whole new way to make things, without replacing paper.",
    prefs: ["experiential", "luxe"],
  },
  {
    id: "turntable",
    name: "Belt-Drive Turntable",
    price: 1250,
    store: "Lumen Lab",
    image: "/products/turntable.svg",
    tags: ["Art", "Social", "Creative"],
    archetype: "cafe-culture",
    why: "Turns their flat into the cafe they are always sitting in.",
    prefs: ["unique", "luxe"],
  },
];

export const QUESTIONS: Question[] = [
  {
    id: "friday",
    prompt: "What is their ideal Friday night?",
    options: [
      { id: "a", label: "Tea, a book, early night", hint: "Quiet and restorative", scores: { "cozy-creative": 3 } },
      { id: "b", label: "Gaming or a new gadget", hint: "Deep in a rabbit hole", scores: { "tech-play": 3 } },
      { id: "c", label: "Dinner somewhere nice", hint: "An excuse to dress up", scores: { "style-glow": 3 } },
      { id: "d", label: "A cafe with friends", hint: "Long conversations", scores: { "cafe-culture": 3 } },
    ],
  },
  {
    id: "weekend",
    prompt: "Pick their weekend energy.",
    options: [
      { id: "a", label: "Slow morning at home", hint: "Nowhere to be", scores: { "cozy-creative": 3 } },
      { id: "b", label: "Trail, gym, or the sea", hint: "Outside and moving", scores: { "active-outdoors": 3 } },
      { id: "c", label: "Cafe hopping", hint: "Sketchbook in bag", scores: { "cafe-culture": 3 } },
      { id: "d", label: "Building or tinkering", hint: "A project on the go", scores: { "tech-play": 3 } },
    ],
  },
  {
    id: "aesthetic",
    prompt: "What is their aesthetic?",
    options: [
      { id: "a", label: "Warm and textured", hint: "Linen, wood, ceramics", scores: { "cozy-creative": 3 } },
      { id: "b", label: "Clean and monochrome", hint: "Minimal, nothing extra", scores: { "tech-play": 2, "cozy-creative": 1 } },
      { id: "c", label: "Polished and elevated", hint: "Always put-together", scores: { "style-glow": 3 } },
      { id: "d", label: "Earthy and practical", hint: "Built to be used", scores: { "active-outdoors": 3 } },
    ],
  },
  {
    id: "spend",
    prompt: "What do they always spend money on?",
    options: [
      { id: "a", label: "Books and candles", hint: "Little comforts", scores: { "cozy-creative": 3 } },
      { id: "b", label: "Tech and upgrades", hint: "The newest thing", scores: { "tech-play": 3 } },
      { id: "c", label: "Skincare and fragrance", hint: "The good stuff", scores: { "style-glow": 3 } },
      { id: "d", label: "Coffee and art supplies", hint: "Fuel and materials", scores: { "cafe-culture": 3 } },
    ],
  },
  {
    id: "timespent",
    prompt: "Where do they spend most of their time?",
    options: [
      { id: "a", label: "Their cosy corner at home", hint: "Blanket, lamp, book", scores: { "cozy-creative": 3 } },
      { id: "b", label: "At their desk or setup", hint: "Screens and gear", scores: { "tech-play": 3 } },
      { id: "c", label: "Out and about", hint: "Rarely sitting still", scores: { "active-outdoors": 2, "style-glow": 1 } },
      { id: "d", label: "In cafes", hint: "Their second home", scores: { "cafe-culture": 3 } },
    ],
  },
  {
    id: "drink",
    prompt: "What is their usual order?",
    options: [
      { id: "a", label: "Matcha latte", hint: "Always matcha", scores: { "cozy-creative": 3 } },
      { id: "b", label: "Specialty coffee, black", hint: "Knows the roaster", scores: { "cafe-culture": 3 } },
      { id: "c", label: "Protein shake", hint: "Post-workout", scores: { "active-outdoors": 2, "tech-play": 1 } },
      { id: "d", label: "Something iced and pretty", hint: "Worth a photo", scores: { "style-glow": 3 } },
    ],
  },
  {
    id: "lightup",
    prompt: "What would make them light up?",
    options: [
      { id: "a", label: "A cosy upgrade for their room", hint: "Softer, warmer", scores: { "cozy-creative": 3 } },
      { id: "b", label: "A gear upgrade", hint: "Better kit", scores: { "tech-play": 2, "active-outdoors": 1 } },
      { id: "c", label: "Something that feels luxurious", hint: "A proper treat", scores: { "style-glow": 3 } },
      { id: "d", label: "Something to make things with", hint: "Creative fuel", scores: { "cafe-culture": 3 } },
    ],
  },
  {
    id: "giftstyle",
    prompt: "When they get a gift, what wins?",
    options: [
      { id: "a", label: "Something practical", hint: "They will use it daily", prefs: ["practical"] },
      { id: "b", label: "Something sentimental", hint: "Meaning over function", prefs: ["personal"] },
      { id: "c", label: "Something unexpected", hint: "They would never pick it themselves", prefs: ["unique"] },
      { id: "d", label: "Something a little luxurious", hint: "A proper treat", prefs: ["luxe"], scores: { "style-glow": 1 } },
    ],
  },
  {
    id: "producttype",
    prompt: "Product or experience person?",
    options: [
      { id: "a", label: "A thing to unwrap", hint: "Nothing beats opening a box", prefs: ["practical"] },
      { id: "b", label: "Something that starts a hobby", hint: "A new thing to get into", prefs: ["experiential"], scores: { "cafe-culture": 1, "cozy-creative": 1 } },
      { id: "c", label: "Something for their space", hint: "Makes home better", prefs: ["home"], scores: { "cozy-creative": 1 } },
      { id: "d", label: "Something for going out", hint: "Comes with them", prefs: ["practical"], scores: { "style-glow": 1, "active-outdoors": 1 } },
    ],
  },
];

/**
 * Fixed, predetermined demo analysis used by the TikTok route.
 * This is illustrative sample data that shows how repost analysis would work.
 * The prototype does not access TikTok and does not read any real account.
 */
export const TIKTOK_DEMO_SIGNALS = [
  { label: "Matcha & cafe drinks", share: 34, note: "12 sample reposts" },
  { label: "Books & reading", share: 27, note: "9 sample reposts" },
  { label: "Cafe culture", share: 23, note: "8 sample reposts" },
  { label: "Cozy / minimal interiors", share: 16, note: "6 sample reposts" },
];

export const TIKTOK_DEMO_ARCHETYPE = "cozy-creative" as const;

export const ANALYSIS_STEPS = [
  "Looking through their interests...",
  "Finding patterns in what they love...",
  "Understanding their style...",
  "Finding the perfect gift...",
];
