import type { Product } from "./types";

/**
 * Real, purchasable products from Saudi-serving specialist retailers and brands.
 *
 * Every entry below was read from the retailer's own product page: the name,
 * the SAR price, the image and the link all come from that page. Nothing here
 * is invented. Prices move, so each row carries the date it was last checked
 * and the UI tells people to confirm with the retailer.
 *
 * Retailers: ZGames, Newtech Store, Decathlon Saudi, Sun & Sand Sports KSA,
 * Qavashop, Rituals KSA, FACES KSA, Jarir Bookstore.
 */

const CHECKED = "2026-09-16";

export const PRODUCTS: Product[] = [
  // ─────────────── Cozy Creative · Jarir Bookstore (books & reading) ───────────────
  {
    id: "jarir-roco-booklight",
    name: "Roco Booklight",
    price: 9,
    store: "Jarir Bookstore",
    image:
      "https://www.jarir.com/cdn-cgi/image/fit=contain,width=800,height=800,quality=85,metadata=none,format=auto/https://ak-asset.jarir.com/akeneo-prod/asset/m1images/4/6/466671.jpg",
    url: "https://www.jarir.com/sa-en/non-branded-book-reading-lights-466671.html",
    priceCheckedOn: CHECKED,
    tags: ["Books", "Cozy", "Minimal"],
    archetype: "cozy-creative",
    why: "They read late — a clip-on light means they can keep going without lighting up the whole room.",
    prefs: ["practical"],
  },
  {
    id: "jarir-mead-notebook",
    name: "Mead Composition Notebook, 7.5 × 9.75 in",
    price: 19,
    store: "Jarir Bookstore",
    image:
      "https://www.jarir.com/cdn-cgi/image/fit=contain,width=800,height=800,quality=85,metadata=none,format=auto/https://ak-asset.jarir.com/akeneo-prod/asset/m1images/2/9/298326.jpg",
    url: "https://www.jarir.com/sa-en/mead-composition-notebook-298326.html",
    priceCheckedOn: CHECKED,
    tags: ["Books", "Minimal", "Creative"],
    archetype: "cozy-creative",
    why: "A simple, well-made notebook for someone who is always writing or journalling.",
    prefs: ["practical"],
  },
  {
    id: "jarir-energizer-booklight",
    name: "Energizer Flexible Booklight",
    price: 40.25,
    store: "Jarir Bookstore",
    image:
      "https://www.jarir.com/cdn-cgi/image/fit=contain,width=800,height=800,quality=85,metadata=none,format=auto/https://ak-asset.jarir.com/akeneo-prod/asset/m1images/3/8/380418.jpg",
    url: "https://www.jarir.com/sa-en/energizer-book-reading-lights-380418.html",
    priceCheckedOn: CHECKED,
    tags: ["Books", "Cozy", "Minimal"],
    archetype: "cozy-creative",
    why: "Bends to whatever angle they read at — a small upgrade to the reading habit they already have.",
    prefs: ["practical"],
  },
  {
    id: "rituals-ayurveda-290",
    name: "Rituals The Ritual of Ayurveda Scented Candle, 290g",
    price: 130,
    store: "Rituals KSA",
    image:
      "https://en-kw.rituals.com/media/catalog/product/cache/09b1bfd32a9cac79553ac0dafdb76307/8/7/8719134212020_1.png",
    url: "https://en-sa.rituals.com/products/at-home/home-fragrance/scented-candles/the-ritual-of-ayurveda-scented-candle-290g-8719134212020.html",
    priceCheckedOn: CHECKED,
    tags: ["Cozy", "Minimal", "Self-care"],
    archetype: "cozy-creative",
    why: "Warm, soft and understated — it suits the calm, minimal corner they like to wind down in.",
    prefs: ["home", "personal"],
  },
  {
    id: "rituals-seshen-candle",
    name: "Rituals The Ritual of Seshen Scented Candle",
    price: 160,
    store: "Rituals KSA",
    image:
      "https://en-kw.rituals.com/media/catalog/product/cache/09b1bfd32a9cac79553ac0dafdb76307/8/7/8719134205763_1.png",
    url: "https://en-sa.rituals.com/products/at-home/home-fragrance/scented-candles/8719134205763-the-ritual-of-seshen-scented-candle.html",
    priceCheckedOn: CHECKED,
    tags: ["Cozy", "Minimal", "Self-care"],
    archetype: "cozy-creative",
    why: "A cosy-lifestyle gift that feels considered without being over the top.",
    prefs: ["home", "personal"],
  },
  {
    id: "rituals-amsterdam-400",
    name: "Rituals Amsterdam Collection Candle, 400g",
    price: 200,
    store: "Rituals KSA",
    image:
      "https://en-kw.rituals.com/media/catalog/product/cache/09b1bfd32a9cac79553ac0dafdb76307/8/7/8719134185966_1.png",
    url: "https://en-sa.rituals.com/products/at-home/home-fragrance/scented-candles/8719134185966-amsterdam-collection-candle-400g.html",
    priceCheckedOn: CHECKED,
    tags: ["Cozy", "Minimal"],
    archetype: "cozy-creative",
    why: "Big enough to be the centrepiece of the room they spend most of their time in.",
    prefs: ["home"],
  },
  {
    id: "rituals-seshen-floating",
    name: "Rituals The Ritual of Seshen Floating Candle",
    price: 275,
    store: "Rituals KSA",
    image:
      "https://en-kw.rituals.com/media/catalog/product/cache/09b1bfd32a9cac79553ac0dafdb76307/8/7/8719134205770_1.png",
    url: "https://en-sa.rituals.com/products/at-home/home-fragrance/scented-candles/8719134205770-the-ritual-of-seshen-floating-candle.html",
    priceCheckedOn: CHECKED,
    tags: ["Cozy", "Art", "Minimal"],
    archetype: "cozy-creative",
    why: "More of an object than a candle — the kind of detail someone with a careful eye notices.",
    prefs: ["home", "unique"],
  },

  // ─────────────── Tech & Play · ZGames + Newtech Store ───────────────
  {
    id: "zgames-joycon-dock",
    name: "K Gaming SW LITE / OLED 4-in-1 Joy-Con Charging Dock, Black",
    price: 29,
    store: "ZGames",
    image:
      "https://zgames.sa/media/catalog/product/cache/cbf5418df84a48f9eaf7f899d2e6bea6/k/_/k_gamings_87.jpg",
    url: "https://zgames.sa/k-gaming-sw-lite-oled-4-in1-joy-con-charging-dock-black",
    priceCheckedOn: CHECKED,
    tags: ["Gaming", "Setup", "Technology"],
    archetype: "tech-play",
    why: "Unglamorous but genuinely useful — it solves the dead-controller problem every Switch player has.",
    prefs: ["practical"],
  },
  {
    id: "zgames-funko-jordan",
    name: "Funko Pop NBA Bulls: Michael Jordan",
    price: 89,
    store: "ZGames",
    image:
      "https://zgames.sa/media/catalog/product/cache/cbf5418df84a48f9eaf7f899d2e6bea6/uploads/uploads/Funko_NBA_3.jpg",
    url: "https://zgames.sa/funko-pop-nba-bulls-michael-16847690332861",
    priceCheckedOn: CHECKED,
    tags: ["Gaming", "Creative", "Setup"],
    archetype: "tech-play",
    why: "A collectible for their desk — specific enough to show you know what they are into.",
    prefs: ["personal", "unique"],
  },
  {
    id: "zgames-battlefield-6",
    name: "Battlefield 6 Standard Edition — PS5",
    price: 299,
    store: "ZGames",
    image:
      "https://zgames.sa/media/catalog/product/cache/cbf5418df84a48f9eaf7f899d2e6bea6/b/a/battlefield_6_gcam_2.jpg",
    url: "https://zgames.sa/battlefield-6-standard-edition-ps5",
    priceCheckedOn: CHECKED,
    tags: ["Gaming", "Technology", "Social"],
    archetype: "tech-play",
    why: "A new release they can actually play this weekend — straightforward and well judged for a gamer.",
    prefs: ["experiential"],
  },
  {
    id: "newtech-razer-ornata-v3",
    name: "Razer Ornata V3 Low-profile Mecha-membrane RGB Keyboard, UK Layout",
    price: 449,
    store: "Newtech Store",
    image:
      "https://cdn.shopify.com/s/files/1/0419/5500/0480/products/razer-ornata-v3-low-profile-mecha-membrane-rgb-keyboard-uk-layout-keyboards-razer-202489.jpg?v=1665189653",
    url: "https://sa.newtechstore.com/products/razer-ornata-v3-rgb-keyboard",
    priceCheckedOn: CHECKED,
    tags: ["Gaming", "Setup", "Technology"],
    archetype: "tech-play",
    why: "A real desk upgrade they will touch every day, and it fits a clean RGB setup.",
    prefs: ["practical"],
  },
  {
    id: "zgames-gameon-monitor",
    name: 'GAMEON GOAM24FHD200IPS Marksman Series 24" FHD 200Hz Gaming Monitor',
    price: 499,
    store: "ZGames",
    image:
      "https://zgames.sa/media/catalog/product/cache/cbf5418df84a48f9eaf7f899d2e6bea6/6/2/6275000580904-1.jpg",
    url: "https://zgames.sa/gameon-goam24fhd200ips-marksman-series-24-fhd-200hz-mprt-0-5ms-hdmi-2-1-fast-ips-gaming-monitor-supports-ps5-white",
    priceCheckedOn: CHECKED,
    tags: ["Gaming", "Setup", "Technology"],
    archetype: "tech-play",
    why: "200Hz makes everything feel smoother — the upgrade a setup-focused gamer notices immediately.",
    prefs: ["practical", "luxe"],
  },
  {
    id: "zgames-asus-gaming-pc",
    name: "Asus B760M Plus Core i5 14th Gen 16GB 1TB SSD RTX 5060 8GB Gaming PC",
    price: 6000,
    store: "ZGames",
    image:
      "https://zgames.sa/media/catalog/product/cache/cbf5418df84a48f9eaf7f899d2e6bea6/z/g/zgames-bundle_70.jpeg",
    url: "https://zgames.sa/asus-760m-core-i5-14th-gen16gb-1tb-ssd-5060-8gb-with-spear-dost60-240-mm-gaming-pc-zgames-exclusive",
    priceCheckedOn: CHECKED,
    tags: ["Gaming", "Technology", "Setup"],
    archetype: "tech-play",
    why: "The big-gesture gift for someone whose whole hobby lives on their PC.",
    prefs: ["luxe"],
  },

  // ─────────────── Style & Glow · FACES KSA + Rituals ───────────────
  {
    id: "faces-mufe-artist-to-go",
    name: "Make Up For Ever Artist to Go Eyeshadow Palette",
    price: 75,
    store: "FACES KSA",
    image:
      "https://www.faces.sa/dw/image/v2/BJSM_PRD/on/demandware.static/-/Sites-faces-master-catalog/default/dwd1ca0669/images/021716624692_1.jpg?sw=800&sh=800",
    url: "https://www.faces.sa/en/p/make-up-for-ever-artist-to-go-eyeshadow-palette-021716624692.html",
    priceCheckedOn: CHECKED,
    tags: ["Beauty", "Self-care", "Minimal"],
    archetype: "style-glow",
    why: "Small, pretty and genuinely usable — an easy win for someone who likes doing their makeup.",
    prefs: ["practical"],
  },
  {
    id: "rituals-precious-amber",
    name: "Rituals Precious Amber Scented Candle",
    price: 200,
    store: "Rituals KSA",
    image:
      "https://en-kw.rituals.com/media/catalog/product/cache/09b1bfd32a9cac79553ac0dafdb76307/8/7/8719134157390_1.png",
    url: "https://en-sa.rituals.com/products/at-home/home-fragrance/scented-candles/8719134157390-preciousamberscentedcandle.html",
    priceCheckedOn: CHECKED,
    tags: ["Luxury", "Self-care", "Cozy"],
    archetype: "style-glow",
    why: "Warm amber, quietly luxurious — a self-care gift that feels more expensive than it is.",
    prefs: ["home", "personal"],
  },
  {
    id: "rituals-karma-840",
    name: "Rituals The Ritual of Karma Scented Candle, 840g",
    price: 260,
    store: "Rituals KSA",
    image:
      "https://en-kw.rituals.com/media/catalog/product/cache/09b1bfd32a9cac79553ac0dafdb76307/8/7/8719134178371_1.png",
    url: "https://en-sa.rituals.com/products/at-home/home-fragrance/scented-candles/8719134178371-the-ritual-of-karma-scented-candle-840g.html",
    priceCheckedOn: CHECKED,
    tags: ["Luxury", "Self-care", "Cozy"],
    archetype: "style-glow",
    why: "The large three-wick version — a proper treat for someone who takes self-care seriously.",
    prefs: ["luxe", "home"],
  },
  {
    id: "faces-givenchy-gentleman-set",
    name: "Givenchy Gentleman Eau De Parfum Gift Set",
    price: 600,
    store: "FACES KSA",
    image:
      "https://www.faces.sa/dw/image/v2/BJSM_PRD/on/demandware.static/-/Sites-faces-master-catalog/default/dw7b6f7587/images/013115715933_1.jpg?sw=800&sh=800",
    url: "https://www.faces.sa/en/p/givenchy-gentleman-gift-set-eau-de-parfum-013115715933.html",
    priceCheckedOn: CHECKED,
    tags: ["Beauty", "Luxury", "Fashion"],
    archetype: "style-glow",
    why: "A complete set rather than a single bottle — it lands as a real occasion gift.",
    prefs: ["personal", "luxe"],
  },
  {
    id: "faces-ysl-y-edp-set",
    name: "Yves Saint Laurent Y EDP Set",
    price: 620,
    store: "FACES KSA",
    image:
      "https://www.faces.sa/dw/image/v2/BJSM_PRD/on/demandware.static/-/Sites-faces-master-catalog/default/dwcae77074/images/034817467285_1.jpg?sw=800&sh=800",
    url: "https://www.faces.sa/en/p/ysl-y-edp-set-034817467285.html",
    priceCheckedOn: CHECKED,
    tags: ["Beauty", "Luxury", "Fashion"],
    archetype: "style-glow",
    why: "A signature-scent set for someone who cares about how they turn up.",
    prefs: ["personal", "luxe"],
  },
  {
    id: "faces-hermes-barenia",
    name: "Hermès Barenia Eau De Parfum",
    price: 835,
    store: "FACES KSA",
    image:
      "https://www.faces.sa/dw/image/v2/BJSM_PRD/on/demandware.static/-/Sites-faces-master-catalog/default/dw928f661b/images/014517796533_1.jpg?sw=800&sh=800",
    url: "https://www.faces.sa/en/p/hermes-barenia-014517796533.html",
    priceCheckedOn: CHECKED,
    tags: ["Beauty", "Luxury", "Fashion"],
    archetype: "style-glow",
    why: "The kind of fragrance they would love but would never buy for themselves.",
    prefs: ["luxe", "unique"],
  },

  // ─────────────── Active & Outdoors · Decathlon Saudi + Sun & Sand Sports ───────────────
  {
    id: "decathlon-resistance-band",
    name: "Pilates Resistance Band 3 kg, Burgundy",
    price: 55,
    store: "Decathlon Saudi",
    image:
      "https://cdn.shopify.com/s/files/1/0553/5707/9704/files/pic_4e72a887-13c6-40d6-8e17-7995842312b8.jpg?v=1789523473",
    url: "https://decathlon.sa/products/pilates-resistance-band-3-kg-burgundy",
    priceCheckedOn: CHECKED,
    tags: ["Fitness", "Energy"],
    archetype: "active-outdoors",
    why: "Packs into any bag — good for someone who trains wherever they happen to be.",
    prefs: ["practical"],
  },
  {
    id: "decathlon-skipping-rope",
    name: "Weighted Skipping Rope 700",
    price: 110,
    store: "Decathlon Saudi",
    image:
      "https://cdn.shopify.com/s/files/1/0553/5707/9704/files/pic_b3cd70a0-df4f-405f-80c1-70616e388c0a.jpg?v=1789525330",
    url: "https://decathlon.sa/products/weighted-skipping-rope-700",
    priceCheckedOn: CHECKED,
    tags: ["Fitness", "Energy"],
    archetype: "active-outdoors",
    why: "A serious bit of cardio kit that costs very little and gets used constantly.",
    prefs: ["practical"],
  },
  {
    id: "decathlon-hex-dumbbell-5kg",
    name: "Hex Dumbbell Cross Training and Weight Training 5 kg, Black",
    price: 165,
    store: "Decathlon Saudi",
    image:
      "https://cdn.shopify.com/s/files/1/0553/5707/9704/files/pic_377a7d3f-8878-4d4b-a5e1-ac4a7065591e.jpg?v=1789524964",
    url: "https://decathlon.sa/products/hex-dumbbell-cross-training-and-weight-training-5kg-black",
    priceCheckedOn: CHECKED,
    tags: ["Fitness", "Energy"],
    archetype: "active-outdoors",
    why: "Solid, no-nonsense kit for someone building a home setup.",
    prefs: ["practical"],
  },
  {
    id: "decathlon-pilates-mat",
    name: "20 mm Thick Ultra-Comfortable Wide Pilates Mat, Black",
    price: 365,
    store: "Decathlon Saudi",
    image:
      "https://cdn.shopify.com/s/files/1/0553/5707/9704/files/pic_c114480c-d9e6-4e94-80a9-b0f4c1cdec43.jpg?v=1789524015",
    url: "https://decathlon.sa/products/20-mm-thick-ultra-comfortable-and-wide-pilates-mat-black",
    priceCheckedOn: CHECKED,
    tags: ["Fitness", "Energy", "Outdoors"],
    archetype: "active-outdoors",
    why: "Thick and wide enough to actually be comfortable — a clear upgrade on a basic mat.",
    prefs: ["practical", "home"],
  },
  {
    id: "sss-nb-1080v15",
    name: "New Balance Men's 1080v15 Running Shoes",
    price: 990,
    store: "Sun & Sand Sports",
    image:
      "https://en-sa.sssports.com/dw/image/v2/BDVB_PRD/on/demandware.static/-/Sites-akeneo-master-catalog/default/dweb8fc13e/sss/SSS2/N/B/M/1/0/SSS2_NBM10804O2_2E_199063064316_1.jpg?sw=800&sh=800",
    url: "https://en-sa.sssports.com/new-balance-mens-1080v15-running-shoes/NBM10804O2-2E.html",
    priceCheckedOn: CHECKED,
    tags: ["Fitness", "Outdoors", "Energy"],
    archetype: "active-outdoors",
    why: "A proper daily trainer for someone putting real distance in — the gift a runner would pick themselves.",
    prefs: ["luxe", "practical"],
  },
  {
    id: "decathlon-trampoline",
    name: "Round Trampoline with Safety Net 365",
    price: 1725,
    store: "Decathlon Saudi",
    image:
      "https://cdn.shopify.com/s/files/1/0553/5707/9704/files/pic_ffba7849-e1a1-42fd-8178-f685e12791a6.jpg?v=1789523372",
    url: "https://decathlon.sa/products/round-trampoline-with-safety-net-365",
    priceCheckedOn: CHECKED,
    tags: ["Outdoors", "Energy", "Fitness"],
    archetype: "active-outdoors",
    why: "Turns the garden into the thing everyone uses — an experience rather than an object.",
    prefs: ["experiential", "luxe"],
  },

  // ─────────────── Café & Culture · Qavashop (Saudi specialty roasters) ───────────────
  {
    id: "qava-roast-maestro-arabica",
    name: "Roast Maestro Filter Coffee Arabica Blend, 250g",
    price: 33.23,
    store: "Qavashop",
    image:
      "https://cdn.qavashop.com/24325-large_default/Roast-Maestro-Filter-Coffee-Arabica-Blend-250g-4974.jpg",
    url: "https://qavashop.com/en/coffee/coffee-beans-deals/Roast-Maestro-Filter-Coffee-Arabica-Blend-250g-4974.html",
    priceCheckedOn: CHECKED,
    tags: ["Coffee", "Creative"],
    archetype: "cafe-culture",
    why: "Freshly roasted filter beans from a Saudi roaster — an easy yes for someone who brews at home.",
    prefs: ["practical", "experiential"],
  },
  {
    id: "qava-bunista-huila",
    name: "Bunista Colombia Huila, 250g",
    price: 39.95,
    store: "Qavashop",
    image:
      "https://cdn.qavashop.com/22368-large_default/Bunista-Colombia-Huila-250g-1978.jpg",
    url: "https://qavashop.com/en/coffee/coffee-beans-deals/Bunista-Colombia-Huila-250g-1978.html",
    priceCheckedOn: CHECKED,
    tags: ["Coffee", "Creative"],
    archetype: "cafe-culture",
    why: "A single-origin from a named Saudi roastery — the sort of thing a coffee person actually notices.",
    prefs: ["unique", "experiential"],
  },
  {
    id: "qava-zelebrity-chelchele",
    name: "Zelebrity Coffee Roaster Ethiopia Chelchele Coffee Beans, 250g",
    price: 47.2,
    store: "Qavashop",
    image:
      "https://cdn.qavashop.com/39852-large_default/Zelebrity-Coffee-Roaster-Ethiopia-Chelchele-Coffee-Beans-250g-5884.jpg",
    url: "https://qavashop.com/en/coffee/filter/Zelebrity-Coffee-Roaster-Ethiopia-Chelchele-Coffee-Beans-250g-5884.html",
    priceCheckedOn: CHECKED,
    tags: ["Coffee", "Creative", "Art"],
    archetype: "cafe-culture",
    why: "A washed Ethiopian for someone who likes their coffee bright and talks about where it came from.",
    prefs: ["unique", "experiential"],
  },
  {
    id: "qava-v60-drip-kit",
    name: "V60 Coffee Drip Kit, 9-Piece Specialty Coffee Set",
    price: 149.73,
    store: "Qavashop",
    image:
      "https://cdn.qavashop.com/40704-large_default/V60-coffee-drip-kit-drip-set-6-pieces-specialty-coffee-set-professional-coffee-maker-tools-barista-drip-coffee-kit-9590.jpg",
    url: "https://qavashop.com/en/brewing-bar/coffee-makers/V60-coffee-drip-kit-drip-set-6-pieces-specialty-coffee-set-professional-coffee-maker-tools-barista-drip-coffee-kit-9590.html",
    priceCheckedOn: CHECKED,
    tags: ["Coffee", "Creative", "Social"],
    archetype: "cafe-culture",
    why: "Everything they need to start brewing pour-over properly — a hobby in a box.",
    prefs: ["experiential", "personal"],
  },
  {
    id: "qava-v60-full-set",
    name: "V60 Set — Server, Dripper, Scale, Kettle, Grinder & Tools Kit",
    price: 240.69,
    store: "Qavashop",
    image:
      "https://cdn.qavashop.com/34325-large_default/v60-set-drip-coffee-maker-server-dripper-scale-kettle-grinder-dosing-cup-and-v60-tools-kit-11706.jpg",
    url: "https://qavashop.com/en/brewing-bar/brewing-kits/v60-set-drip-coffee-maker-server-dripper-scale-kettle-grinder-dosing-cup-and-v60-tools-kit-11706.html",
    priceCheckedOn: CHECKED,
    tags: ["Coffee", "Creative", "Social"],
    archetype: "cafe-culture",
    why: "The full café-at-home setup, down to the scale and grinder — a serious gift for a coffee obsessive.",
    prefs: ["experiential", "unique"],
  },
  {
    id: "qava-sage-barista-express",
    name: "Sage The Barista Express Coffee Machine SES875",
    price: 2879.37,
    store: "Qavashop",
    image:
      "https://cdn.qavashop.com/37791-large_default/Sage-SES875UK-The-Barista-Express-Coffee-Machine-3996.jpg",
    url: "https://qavashop.com/en/espresso-machines/thermoblock/Sage-SES875UK-The-Barista-Express-Coffee-Machine-3996.html",
    priceCheckedOn: CHECKED,
    tags: ["Coffee", "Social", "Setup"],
    archetype: "cafe-culture",
    why: "Grinder and espresso machine in one — their café habit, moved into the kitchen.",
    prefs: ["luxe", "experiential"],
  },
];
